### ISSUE TITLE
Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by Smip** [taromero/swal-forms#1]
Error: Uncaught NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
For line: 123
sweetAlertModal.insertBefore(formTag, cancelButtonTag);

**Comment by taromero** [comment]
Please provide a bit of context (an indicative issue name would be nice too).
1. Does this happen on initialization?
2. Which version of Sweet Alert are you using?

Please check the live example on the readme to see if there's anything different.

**Comment by taromero** [comment]
Closing this since I didn't receive any feedback. @Smip please reopen this ticket if you have more info.

**Comment by taromero** [comment]
This was an error with newer versions of Sweet Alert. Just fixed it.
