### ISSUE TITLE
Space submits form

### ISSUE THREAD

**Issue by Wayn0** [taromero/swal-forms#11]
Hi,

Is anyone else seeing this? 
When typing in a text field on a swal-form hitting the space bar submits the form.

Thanks
Wayn0

**Comment by taromero** [comment]
I cannot reproduce it on the live example (using Chrome): https://cdn.rawgit.com/taromero/swal-forms/master/live-demo/live-demo.html. Could you provide a reproduction case in a JSFiddle (or the like), indicating the browser and swal-forms version (commit)?

Thanks!

**Comment by Wayn0** [comment]
Wow, thanks for the quick response man :-)

Can't reproduce with the live demo.

JsFiddle demonstrating the issue.
https://jsfiddle.net/za7mvfqj/2/

swal version: 
swal-forms commit: 92a912e4dac46e08d92035e65347a3ce1c533da1 (most recent I believe)

Firefox 44.0 on Ubuntu 15.10
Chromium on Ubuntu 15.10
Chrome 48 on Windows 7

Thanks, anything else you would like me to test?

**Comment by taromero** [comment]
I just tested it again and this only seems to happen with the specific version of sweet-alert that is linked in the jsfiddle. By replacing that lib with either the lib that is currently available for download on sweet-alert's site or by https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js, the problem doesn't happen.

Which is the version (commit) of sweet-alert that you point to?

**Comment by Wayn0** [comment]
Thank you sir, updating to the latest sweet-alert fixed the issue. 
The version I was using came bundled with code I was handed, so it does not have any version strings.

Thanks for your help, hopefully if anyone else experiences the same problem they will find this issue.

Great work by the way, these form really speed up input :-)

**Comment by taromero** [comment]
Thanks for reporting!
