### ISSUE TITLE
Scroll

### ISSUE THREAD

**Issue by karmendra** [taromero/swal-forms#12]
If there are  more fields than they get hidden below and there is no scrollbar to reach them.

**Comment by brunovcosta** [comment]
you can use an css to fix this, changing the `swal-form` overflow to scroll

**Comment by karmendra** [comment]
Thanks for you response. I tried adding `overflow: auto !important;` to swal-form css, but it didn't work. I see the same problem in the [demo page](https://cdn.rawgit.com/taromero/swal-forms/master/live-demo/live-demo.html) as well. You should try it on 14" or 15" screen to see the issue.

**Comment by taromero** [comment]
Sorry for the delay, I'll try to address this issue this week.

**Comment by lancedouglas1** [comment]
This is my only real issue with swal-forms.  In a perfect world, I would like to be able to "stick" the popup to the top-center, bottom-center, or leftside-top, leftside-bottom, etc....  But I would be happy with the ability to scroll the contents of the popup, or even just the parent page.

**Comment by taromero** [comment]
This should have been addressed by #16. Please reopen this ticket if it was not.
