### ISSUE TITLE
incompatibility with current sweet alert version?

### ISSUE THREAD

**Issue by antonioaltamura** [taromero/swal-forms#13]
I'm not sure why the form fields are simply hided (with display:none)

https://jsfiddle.net/alfredopacino/tmoLfsdf/

**Comment by taromero** [comment]
Sorry for the delay, I'll try to look at this some day this week.

**Comment by antonioaltamura** [comment]
i've just messed up the swal-forms css file. There is no incompatibility here :)
Congrats for your work :+1:

**Comment by taromero** [comment]
Thanks for the update!
