### ISSUE TITLE
npm or browserify support?

### ISSUE THREAD

**Issue by rico345100** [taromero/swal-forms#26]
I really interested in this module. I'm using swal as npm module, but looks like this is not. Is there a plan to support npm or browserify?

**Comment by emberdart** [comment]
I made a pull request for updates to the package.json which hopefully should be accepted.
Until then you can use `npm --save install dandart/swal-forms` or add `"swal-forms": "github:dandart/swal-forms"` to your dependency section of package.json.

I haven't updated any code so it should be as simple as `require('swal-forms')` which would overwrite the original global (which iirc think is still present in the original swal?).

That'll probably need some exports later on.

**Comment by rico345100** [comment]
I don't know what am I wrong, but just import your module wasn't worked at all, so I leave my solution here:

import css files in entry js file:

```
import 'sweetalert/dist/sweetalert.css';
import 'swal-forms/swal-forms.css';
```

and then create another js file what ever you like, I named swal-hack.js:

```
import swal from 'sweetalert';
import 'swal-forms';

swal.withForm({
    title: 'Cool Swal-Forms example with no explicit placeholder',
    formFields: [
        { id: 'sampleIdField'}
    ]
});

export function swalForm(options) {
    return swal.withForm(options);
}
```

Now, there you go. You can now use swal-from like this:

```
import { swalForm } from 'swal-forms';

swalForm({ ... });
```

swal-forms is really great module, so I hope lots of people using it. Enjoy!

**Comment by emberdart** [comment]
Yeah, the module didn't work on its own, it needs a global/scope to overwrite for now...

**Comment by emberdart** [comment]
I'd make it export properly soon, so you can use it on its own, and it'll just require sweetalert if not already required, then export sweetalert with extra modules added on. I think that's the best way of doing it, rather than exporting a wrapper that accepts an existing sweetalert, or a global overwriter.
