### ISSUE TITLE
Add selected to option

### ISSUE THREAD

**Issue by splash58** [taromero/swal-forms#35]
Just add one line to the function and change the next one a little

 ```
function toHtmlOptions (optionsString, option) {
     option.selected = ((typeof option.selected !== 'undefined') && option.selected) ? ' selected' : ''
     return optionsString + t("<option value='{value}' {selected}>{text}</option>", option)
 }
```
and, for example,   `{value: '3', text: 'test3', selected:true},` can be used to select an option

**Comment by pthomas931** [comment]
This change is currently in master. https://github.com/taromero/swal-forms/commit/a40c077f80d8251c355fa7da927a9533779dc075

**Comment by taromero** [comment]
Thanks for the notification @pthomas931, closing this one!
