### ISSUE TITLE
Not working with Sweet Alert 2?

### ISSUE THREAD

**Issue by samir-kamble** [taromero/swal-forms#39]
Guys,
I have recently upgraded to Sweet alert2 and found that my forms are not appearing on the SWAL popups. Can you please guide if it is version issue of something else?

Regards,
Sam

**Comment by taromero** [comment]
Haven't tried out yet, but from a quick look seems like [https://github.com/limonte/sweetalert2](sweetalert2) having different CSS selectors than [https://github.com/t4t5/sweetalert](sweetalert). Compatibilty would mean at least handling a different set of selectors depending on the library in use (there can be other problems, would have to check).

I'll try to give it a try this week, though PRs are welcome.

**Comment by samir-kamble** [comment]
I got it resolved. Got solution in Swal to Swal2 migration guide.

Swal2 has inbuilt input capabilities which was missing in Swal. Just used
that and solved it.

On Sep 15, 2017 8:51 AM, "Tomas Romero" <notifications@github.com> wrote:

Haven't tried out yet, but from a quick look seems like
https://github.com/limonte/sweetalert2 <http://sweetalert2> having
different CSS selectors than https://github.com/t4t5/sweetalert
<http://sweetalert>. Compatibilty would mean at least handling a different
set of selectors depending on the library in use (there can be other
problems, would have to check).

I'll try to give it a try this week, though PRs are welcome.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/taromero/swal-forms/issues/39#issuecomment-329669469>,
or mute the thread

**Comment by taromero** [comment]
Closing this since the user reported it has solved it, and I'll not work on this at least in the short term.

**Comment by soza64** [comment]
Hello World!
