### ISSUE TITLE
Forms interfering

### ISSUE THREAD

**Issue by brunovcosta** [taromero/swal-forms#5]
`swal( ...  )` have the forms after previous `swal.withForms({ ... })` calls

**Comment by brunovcosta** [comment]
solved in 6b0cd473d1b85a83ad0f19b017a7b42acb2e2c47

**Comment by taromero** [comment]
Hey sorry for the delay, I'll try to take a look at this between today and
tomorrow.

**Comment by taromero** [comment]
The proposed fix has been integrated to the main branch.
